# Generated by Django 5.1 on 2024-08-19 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('new_item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('exchange_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_name', models.CharField(max_length=255)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_main_category', to='accounts.category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_sub_category', to='accounts.subcategory')),
            ],
        ),
    ]
