# Generated by Django 5.1 on 2024-08-19 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='exchange_amount',
        ),
        migrations.AddField(
            model_name='exchange',
            name='additional_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exchange',
            name='estimated_exchange_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
