# Generated by Django 5.1 on 2024-08-20 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_exchange_commission_amount_exchange_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='new_item_main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_new_main_category', to='accounts.category'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='new_item_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_new_sub_category', to='accounts.subcategory'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('debit', 'Debit'), ('telebirr', 'telebirr')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('debit', 'Debit'), ('telebirr', 'telebirr')], default='cash', max_length=50),
        ),
    ]
