# Generated by Django 5.1 on 2024-08-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronics',
            name='added_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
